ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 20.0
    two_d_mode: true
    publish_tf: true
    predict_to_current_time: true
    sensor_timeout: 0.2
    transform_time_offset: 0.00
    transform_timeout: 0.2

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Entrada do serial_node
    odom0: odom
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # x, y, z,   roll, pitch, yaw,   vx, vy, vz,   vroll, vpitch, vyaw,   ax, ay, az
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true, false,
                   false, false, true,
                   false, false, true]


#    imu0: /imu/data  # só se estiver confiável
#    imu0_config: [false, false, false,
#                  true,  true,  true,
#                  false, false, false,
#                  true,  true,  true,
#                  true,  true,  true]
#    imu0_relative: true
#    imu0_remove_gravitational_acceleration: true
