amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: "scan"
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    laser_model_type: "likelihood_field"
    update_min_d: 0.05
    update_min_a: 0.05
    resample_interval: 2
    transform_tolerance: 1.0
    recovery_behavior_enabled: true
    gui_publish_rate: 10.0
    save_pose_rate: 0.5
    use_map_topic: true
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    laser_min_range: 0.1
    laser_max_range: 12.0

map_server:
  ros__parameters:
    use_sim_time: false
    # OBS: este path será sobreposto pelo argumento 'map' no launch quando você lançar direto.
    yaml_filename: "/home/robo/ros2_ws/meu_mapa_final.yaml"

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.4
      use_astar: false
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    current_goal_checker: "general_goal_checker"

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.20
      max_linear_accel: 0.4
      max_linear_decel: 0.4
      lookahead_dist: 0.5
      min_lookahead_dist: 0.28
      max_lookahead_dist: 0.8
      lookahead_time: 1.0
      use_velocity_scaled_lookahead_dist: true
      use_rotate_to_heading: false     # DESLIGAR inicialmente
      allow_reversing: false           # DESLIGAR inicialmente
      min_approach_linear_velocity: 0.10
      use_interpolation: true
      transform_timeout: 0.5
      transform_tolerance: 0.5
      max_angular_accel: 2.0
      max_robot_pose_search_dist: 10.0

      progress_checker_plugin: "progress_checker"
      goal_checker_plugins: ["general_goal_checker"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.06
      movement_time_allowance: 20.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.18
      yaw_goal_tolerance: 0.30
      stateful: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      transform_tolerance: 0.5
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: "odom"
      robot_base_frame: "base_link"
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05
      robot_radius: 0.30
      plugins: ["inflation_layer", "obstacle_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: "/scan"
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_range: 6.0
          raytrace_range: 8.0
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.35
        cost_scaling_factor: 4.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      transform_tolerance: 0.3
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_link"
      resolution: 0.05
      track_unknown_space: true
      robot_radius: 0.30
      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        enabled: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.45
        cost_scaling_factor: 4.0

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    feedback: "OPEN_LOOP"
    odom_topic: "/odometry/filtered"
    max_velocity: [0.26, 0.0, 0.8]
    min_velocity: [0.0, 0.0, 0.0]
    max_accel:    [0.5, 0.0, 1.8]
    max_decel:    [-0.5, 0.0, -1.8]
    velocity_timeout: 0.5
